package com.usersmanagement.model;

// Generated Dec 19, 2016 1:27:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TblApplications generated by hbm2java
 */
public class TblApplications implements java.io.Serializable {

	private int applicationId;
	private String applicationname;
	private Set tblPermissionses = new HashSet(0);

	public TblApplications() {
	}

	public TblApplications(int applicationId) {
		this.applicationId = applicationId;
	}

	public TblApplications(int applicationId, String applicationname,
			Set tblPermissionses) {
		this.applicationId = applicationId;
		this.applicationname = applicationname;
		this.tblPermissionses = tblPermissionses;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public String getApplicationname() {
		return this.applicationname;
	}

	public void setApplicationname(String applicationname) {
		this.applicationname = applicationname;
	}

	public Set getTblPermissionses() {
		return this.tblPermissionses;
	}

	public void setTblPermissionses(Set tblPermissionses) {
		this.tblPermissionses = tblPermissionses;
	}

}
