package com.usersmanagement.model;

// Generated Dec 19, 2016 1:27:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TblUsers generated by hbm2java
 */
public class TblUsers implements java.io.Serializable {

	private int usersId;
	private String email;
	private String password;
	private int managerId;
	private Set tbleRoleses = new HashSet(0);

	public TblUsers() {
	}

	public TblUsers(int usersId, int managerId) {
		this.usersId = usersId;
		this.managerId = managerId;
	}

	public TblUsers(int usersId, String email, String password, int managerId,
			Set tbleRoleses) {
		this.usersId = usersId;
		this.email = email;
		this.password = password;
		this.managerId = managerId;
		this.tbleRoleses = tbleRoleses;
	}

	public int getUsersId() {
		return this.usersId;
	}

	public void setUsersId(int usersId) {
		this.usersId = usersId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getManagerId() {
		return this.managerId;
	}

	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	public Set getTbleRoleses() {
		return this.tbleRoleses;
	}

	public void setTbleRoleses(Set tbleRoleses) {
		this.tbleRoleses = tbleRoleses;
	}

}
