package com.usersmanagement.model;

//Generated Dec 21, 2016 5:48:01 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
* TblPermissions generated by hbm2java
*/
@Entity(name = "tbl_permissions")
public class PermissionEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int permissionId;
	private String permissionname;
	
	public PermissionEntity() {
	}

	public PermissionEntity(int permissionId) {
		this.permissionId = permissionId;
	}

	public PermissionEntity(int permissionId, String permissionname) {
		this.permissionId = permissionId;
		this.permissionname = permissionname;
	}

	@Id
	@Column(name = "permission_id", unique = true, nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "permissionname")
	public String getPermissionname() {
		return this.permissionname;
	}

	public void setPermissionname(String permissionname) {
		this.permissionname = permissionname;
	}

}

