package com.usersmanagement.model;

//Generated Dec 21, 2016 5:48:01 PM by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
* TbleRoles generated by hbm2java
*/
@Entity(name = "tble_roles")
public class RoleEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int roleId;
	private String rolenames;
	private List<PermissionEntity> permissions;
	

	

	public RoleEntity() {
	}

	public RoleEntity(int roleId) {
		this.roleId = roleId;
	}

	public RoleEntity(int roleId, String rolenames) {
		this.roleId = roleId;
		this.rolenames = rolenames;
		
	}

	@Id
	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "rolenames")
	public String getRolenames() {
		return this.rolenames;
	}

	public void setRolenames(String rolenames) {
		this.rolenames = rolenames;
	}
	
	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name="tbl_rolespermissions", 
	joinColumns=@JoinColumn(name="role_id"), 
	inverseJoinColumns=@JoinColumn(name="permission_id"))
	public List<PermissionEntity> getPermissions() {
		return permissions;
	}

	public void setPermissions(List<PermissionEntity> permissions) {
		this.permissions = permissions;
	}


}
